# Generated by Django 4.2.7 on 2025-11-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_create_invite_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='page_config',
            field=models.JSONField(blank=True, default=dict, help_text='Canvas-based page configuration with elements, background, theme for invitation page'),
        ),
        migrations.AlterField(
            model_name='event',
            name='additional_photos',
            field=models.JSONField(blank=True, default=list, help_text='Array of up to 5 photo URLs or data URLs (deprecated - use page_config)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.TextField(blank=True, help_text='Banner image URL or data URL for public invitation page (deprecated - use page_config)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Rich text description for public invitation page (deprecated - use page_config)'),
        ),
    ]
