# Generated by Django 4.2.7 on 2025-11-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_add_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='page_config',
            field=models.JSONField(blank=True, default=dict, help_text='Living Poster invitation page configuration with theme, hero, description'),
        ),
    ]
