# Generated by Django 4.2.7 on 2025-11-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_page_config'),
    ]

    operations = [
        migrations.RunSQL(
            # Remove the design_template column if it exists
            sql="ALTER TABLE events DROP COLUMN IF EXISTS design_template;",
            reverse_sql="ALTER TABLE events ADD COLUMN design_template VARCHAR(50) NOT NULL DEFAULT '';",
        ),
    ]
