# Generated by Django 4.2.7 on 2025-11-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_remove_design_template'),
    ]

    operations = [
        migrations.RunSQL(
            # Remove the design_config column if it exists
            sql="ALTER TABLE events DROP COLUMN IF EXISTS design_config;",
            reverse_sql="ALTER TABLE events ADD COLUMN design_config JSONB NOT NULL DEFAULT '{}';",
        ),
    ]
