# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_remove_design_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Soft delete flag - guest is removed but record preserved'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Soft delete flag - RSVP is removed but record preserved'),
        ),
    ]

