# Generated by Django 4.2.7

from django.db import migrations, models, connection


def add_is_removed_if_not_exists(apps, schema_editor):
    """Add is_removed column only if it doesn't exist"""
    db_alias = schema_editor.connection.alias
    
    with connection.cursor() as cursor:
        # Check if column exists in guests table
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='guests' AND column_name='is_removed'
        """)
        if not cursor.fetchone():
            cursor.execute("ALTER TABLE guests ADD COLUMN is_removed BOOLEAN DEFAULT FALSE")
        
        # Check if column exists in rsvps table
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='rsvps' AND column_name='is_removed'
        """)
        if not cursor.fetchone():
            cursor.execute("ALTER TABLE rsvps ADD COLUMN is_removed BOOLEAN DEFAULT FALSE")


def reverse_add_is_removed(apps, schema_editor):
    """Remove is_removed column if it exists"""
    db_alias = schema_editor.connection.alias
    
    with connection.cursor() as cursor:
        # Check if column exists before dropping
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='guests' AND column_name='is_removed'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE guests DROP COLUMN is_removed")
        
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='rsvps' AND column_name='is_removed'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE rsvps DROP COLUMN is_removed")


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_remove_design_config'),
    ]

    operations = [
        migrations.RunPython(add_is_removed_if_not_exists, reverse_add_is_removed),
    ]

