# Generated by Django 4.2.7 on 2025-12-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_add_is_removed_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Date when event expires (for impact calculation)', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='whatsapp_message_template',
            field=models.TextField(blank=True, help_text='Custom WhatsApp message template for sharing'),
        ),
    ]
