# Generated by Django 4.2.7 on 2025-12-31 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_add_template_defaults_and_custom_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='whatsapptemplate',
            new_name='whatsapp_te_event_i_c0c43c_idx',
            old_name='whatsapp_te_event_i_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsapptemplate',
            new_name='whatsapp_te_event_i_74bedc_idx',
            old_name='whatsapp_te_event_i_idx2',
        ),
        migrations.RenameIndex(
            model_name='whatsapptemplate',
            new_name='whatsapp_te_event_i_683f48_idx',
            old_name='whatsapp_te_event_i_idx3',
        ),
        migrations.RenameIndex(
            model_name='whatsapptemplate',
            new_name='whatsapp_te_is_syst_e230e8_idx',
            old_name='whatsapp_te_is_syst_idx',
        ),
    ]
