# Generated by Django 4.2.7 on 2026-01-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_rename_whatsapp_te_event_i_idx_whatsapp_te_event_i_c0c43c_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invitepage',
            index=models.Index(fields=['slug', 'is_published'], name='invite_slug_pub_idx'),
        ),
    ]
