# Generated by Django 4.2.7 on 2026-01-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_invitepage_invite_slug_pub_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subevent',
            index=models.Index(fields=['event', 'is_public_visible', 'is_removed'], name='sub_events_event_visible_idx'),
        ),
        migrations.AddIndex(
            model_name='subevent',
            index=models.Index(fields=['event', 'is_removed', 'start_at'], name='sub_events_event_order_idx'),
        ),
    ]
