# Generated by Django 4.2.7 on 2026-01-01 18:21

from django.db import migrations
from django.db.models.functions import Lower


def normalize_slugs_to_lowercase(apps, schema_editor):
    """Normalize all existing slugs to lowercase"""
    Event = apps.get_model('events', 'Event')
    InvitePage = apps.get_model('events', 'InvitePage')
    
    # Normalize Event slugs
    Event.objects.update(slug=Lower('slug'))
    
    # Normalize InvitePage slugs
    InvitePage.objects.update(slug=Lower('slug'))


def reverse_normalize_slugs(apps, schema_editor):
    """Reverse migration - cannot restore original case, so this is a no-op"""
    # Cannot reverse case normalization, so this is intentionally a no-op
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_subevent_sub_events_event_visible_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_slugs_to_lowercase, reverse_normalize_slugs),
    ]
