# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_create_system_default_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='invitation_sent',
            field=models.BooleanField(default=False, help_text='Whether invitation has been sent to this guest'),
        ),
        migrations.AddField(
            model_name='guest',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when invitation was sent', null=True),
        ),
    ]

