# Generated by Django 4.2.7 on 2026-03-10 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0046_add_invite_design_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreetingCardSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('background_image_url', models.URLField(max_length=500)),
                ('text_overlays', models.JSONField(default=list, help_text='Same shape as ImageTile.settings.textOverlays — placeholder text positioned on the card.')),
                ('tags', models.JSONField(default=list, help_text='e.g. ["wedding", "floral", "minimalist"]')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='greeting_card_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'greeting_card_samples',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
