# Generated by Django 4.2.7 on 2026-03-12 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_add_registry_page_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsbatchrun',
            options={'ordering': ['-collection_window_start']},
        ),
    ]
