# Generated by Django 4.2.7 on 2026-04-19 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0060_rename_invitedesigntemplate_to_invitepagelayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitepagelayout',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invite_page_layouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitepagelayout',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_invite_page_layouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitepagelayout',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_invite_page_layouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
