# Generated by Django 4.2.7 on 2026-04-21 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0061_alter_invitepagelayout_staff_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaApprovedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('preview_text', models.TextField(help_text='Template body shown to hosts. Use [name], [event_title] etc.')),
                ('meta_template_name', models.CharField(help_text='Exact name registered in Meta Business Manager.', max_length=100, unique=True)),
                ('meta_template_language', models.CharField(default='en', max_length=10)),
                ('message_type', models.CharField(choices=[('invitation', 'Invitation'), ('reminder', 'Reminder'), ('update', 'Update'), ('venue_change', 'Venue Change'), ('time_change', 'Time Change'), ('thank_you', 'Thank You'), ('custom', 'Custom')], default='invitation', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_approved_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meta_approved_templates',
                'ordering': ['message_type', 'display_name'],
            },
        ),
    ]
