# Generated by Django 4.2.7 on 2026-04-21 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0062_add_meta_approved_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guest_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_segments', to='events.event')),
            ],
            options={
                'db_table': 'guest_segments',
                'ordering': ['name'],
                'unique_together': {('event', 'name')},
            },
        ),
    ]
