# Generated by Django 4.2.7 on 2026-06-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0093_remove_registry_page_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='has_registry',
            field=models.BooleanField(default=True, help_text='Enable Gift Registry functionality for this event'),
        ),
    ]
