// Comprehensive list of ISO 3166-1 alpha-2 country codes and phone codes
// Based on ITU-T E.164 international numbering plan

export interface CountryInfo {
  code: string
  name: string
  flag: string
}

export const COUNTRY_CODES: Record<string, CountryInfo> = {
  'AD': { code: '+376', name: 'Andorra', flag: '🇦🇩' },
  'AE': { code: '+971', name: 'United Arab Emirates', flag: '🇦🇪' },
  'AF': { code: '+93', name: 'Afghanistan', flag: '🇦🇫' },
  'AG': { code: '+1', name: 'Antigua and Barbuda', flag: '🇦🇬' },
  'AI': { code: '+1', name: 'Anguilla', flag: '🇦🇮' },
  'AL': { code: '+355', name: 'Albania', flag: '🇦🇱' },
  'AM': { code: '+374', name: 'Armenia', flag: '🇦🇲' },
  'AO': { code: '+244', name: 'Angola', flag: '🇦🇴' },
  'AQ': { code: '+672', name: 'Antarctica', flag: '🇦🇶' },
  'AR': { code: '+54', name: 'Argentina', flag: '🇦🇷' },
  'AS': { code: '+1', name: 'American Samoa', flag: '🇦🇸' },
  'AT': { code: '+43', name: 'Austria', flag: '🇦🇹' },
  'AU': { code: '+61', name: 'Australia', flag: '🇦🇺' },
  'AW': { code: '+297', name: 'Aruba', flag: '🇦🇼' },
  'AX': { code: '+358', name: 'Åland Islands', flag: '🇦🇽' },
  'AZ': { code: '+994', name: 'Azerbaijan', flag: '🇦🇿' },
  'BA': { code: '+387', name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  'BB': { code: '+1', name: 'Barbados', flag: '🇧🇧' },
  'BD': { code: '+880', name: 'Bangladesh', flag: '🇧🇩' },
  'BE': { code: '+32', name: 'Belgium', flag: '🇧🇪' },
  'BF': { code: '+226', name: 'Burkina Faso', flag: '🇧🇫' },
  'BG': { code: '+359', name: 'Bulgaria', flag: '🇧🇬' },
  'BH': { code: '+973', name: 'Bahrain', flag: '🇧🇭' },
  'BI': { code: '+257', name: 'Burundi', flag: '🇧🇮' },
  'BJ': { code: '+229', name: 'Benin', flag: '🇧🇯' },
  'BL': { code: '+590', name: 'Saint Barthélemy', flag: '🇧🇱' },
  'BM': { code: '+1', name: 'Bermuda', flag: '🇧🇲' },
  'BN': { code: '+673', name: 'Brunei', flag: '🇧🇳' },
  'BO': { code: '+591', name: 'Bolivia', flag: '🇧🇴' },
  'BQ': { code: '+599', name: 'Caribbean Netherlands', flag: '🇧🇶' },
  'BR': { code: '+55', name: 'Brazil', flag: '🇧🇷' },
  'BS': { code: '+1', name: 'Bahamas', flag: '🇧🇸' },
  'BT': { code: '+975', name: 'Bhutan', flag: '🇧🇹' },
  'BV': { code: '+47', name: 'Bouvet Island', flag: '🇧🇻' },
  'BW': { code: '+267', name: 'Botswana', flag: '🇧🇼' },
  'BY': { code: '+375', name: 'Belarus', flag: '🇧🇾' },
  'BZ': { code: '+501', name: 'Belize', flag: '🇧🇿' },
  'CA': { code: '+1', name: 'Canada', flag: '🇨🇦' },
  'CC': { code: '+61', name: 'Cocos Islands', flag: '🇨🇨' },
  'CD': { code: '+243', name: 'DR Congo', flag: '🇨🇩' },
  'CF': { code: '+236', name: 'Central African Republic', flag: '🇨🇫' },
  'CG': { code: '+242', name: 'Republic of the Congo', flag: '🇨🇬' },
  'CH': { code: '+41', name: 'Switzerland', flag: '🇨🇭' },
  'CI': { code: '+225', name: 'Côte d\'Ivoire', flag: '🇨🇮' },
  'CK': { code: '+682', name: 'Cook Islands', flag: '🇨🇰' },
  'CL': { code: '+56', name: 'Chile', flag: '🇨🇱' },
  'CM': { code: '+237', name: 'Cameroon', flag: '🇨🇲' },
  'CN': { code: '+86', name: 'China', flag: '🇨🇳' },
  'CO': { code: '+57', name: 'Colombia', flag: '🇨🇴' },
  'CR': { code: '+506', name: 'Costa Rica', flag: '🇨🇷' },
  'CU': { code: '+53', name: 'Cuba', flag: '🇨🇺' },
  'CV': { code: '+238', name: 'Cape Verde', flag: '🇨🇻' },
  'CW': { code: '+599', name: 'Curaçao', flag: '🇨🇼' },
  'CX': { code: '+61', name: 'Christmas Island', flag: '🇨🇽' },
  'CY': { code: '+357', name: 'Cyprus', flag: '🇨🇾' },
  'CZ': { code: '+420', name: 'Czech Republic', flag: '🇨🇿' },
  'DE': { code: '+49', name: 'Germany', flag: '🇩🇪' },
  'DJ': { code: '+253', name: 'Djibouti', flag: '🇩🇯' },
  'DK': { code: '+45', name: 'Denmark', flag: '🇩🇰' },
  'DM': { code: '+1', name: 'Dominica', flag: '🇩🇲' },
  'DO': { code: '+1', name: 'Dominican Republic', flag: '🇩🇴' },
  'DZ': { code: '+213', name: 'Algeria', flag: '🇩🇿' },
  'EC': { code: '+593', name: 'Ecuador', flag: '🇪🇨' },
  'EE': { code: '+372', name: 'Estonia', flag: '🇪🇪' },
  'EG': { code: '+20', name: 'Egypt', flag: '🇪🇬' },
  'EH': { code: '+212', name: 'Western Sahara', flag: '🇪🇭' },
  'ER': { code: '+291', name: 'Eritrea', flag: '🇪🇷' },
  'ES': { code: '+34', name: 'Spain', flag: '🇪🇸' },
  'ET': { code: '+251', name: 'Ethiopia', flag: '🇪🇹' },
  'FI': { code: '+358', name: 'Finland', flag: '🇫🇮' },
  'FJ': { code: '+679', name: 'Fiji', flag: '🇫🇯' },
  'FK': { code: '+500', name: 'Falkland Islands', flag: '🇫🇰' },
  'FM': { code: '+691', name: 'Micronesia', flag: '🇫🇲' },
  'FO': { code: '+298', name: 'Faroe Islands', flag: '🇫🇴' },
  'FR': { code: '+33', name: 'France', flag: '🇫🇷' },
  'GA': { code: '+241', name: 'Gabon', flag: '🇬🇦' },
  'GB': { code: '+44', name: 'United Kingdom', flag: '🇬🇧' },
  'GD': { code: '+1', name: 'Grenada', flag: '🇬🇩' },
  'GE': { code: '+995', name: 'Georgia', flag: '🇬🇪' },
  'GF': { code: '+594', name: 'French Guiana', flag: '🇬🇫' },
  'GG': { code: '+44', name: 'Guernsey', flag: '🇬🇬' },
  'GH': { code: '+233', name: 'Ghana', flag: '🇬🇭' },
  'GI': { code: '+350', name: 'Gibraltar', flag: '🇬🇮' },
  'GL': { code: '+299', name: 'Greenland', flag: '🇬🇱' },
  'GM': { code: '+220', name: 'Gambia', flag: '🇬🇲' },
  'GN': { code: '+224', name: 'Guinea', flag: '🇬🇳' },
  'GP': { code: '+590', name: 'Guadeloupe', flag: '🇬🇵' },
  'GQ': { code: '+240', name: 'Equatorial Guinea', flag: '🇬🇶' },
  'GR': { code: '+30', name: 'Greece', flag: '🇬🇷' },
  'GS': { code: '+500', name: 'South Georgia', flag: '🇬🇸' },
  'GT': { code: '+502', name: 'Guatemala', flag: '🇬🇹' },
  'GU': { code: '+1', name: 'Guam', flag: '🇬🇺' },
  'GW': { code: '+245', name: 'Guinea-Bissau', flag: '🇬🇼' },
  'GY': { code: '+592', name: 'Guyana', flag: '🇬🇾' },
  'HK': { code: '+852', name: 'Hong Kong', flag: '🇭🇰' },
  'HM': { code: '+672', name: 'Heard Island', flag: '🇭🇲' },
  'HN': { code: '+504', name: 'Honduras', flag: '🇭🇳' },
  'HR': { code: '+385', name: 'Croatia', flag: '🇭🇷' },
  'HT': { code: '+509', name: 'Haiti', flag: '🇭🇹' },
  'HU': { code: '+36', name: 'Hungary', flag: '🇭🇺' },
  'ID': { code: '+62', name: 'Indonesia', flag: '🇮🇩' },
  'IE': { code: '+353', name: 'Ireland', flag: '🇮🇪' },
  'IL': { code: '+972', name: 'Israel', flag: '🇮🇱' },
  'IM': { code: '+44', name: 'Isle of Man', flag: '🇮🇲' },
  'IN': { code: '+91', name: 'India', flag: '🇮🇳' },
  'IO': { code: '+246', name: 'British Indian Ocean Territory', flag: '🇮🇴' },
  'IQ': { code: '+964', name: 'Iraq', flag: '🇮🇶' },
  'IR': { code: '+98', name: 'Iran', flag: '🇮🇷' },
  'IS': { code: '+354', name: 'Iceland', flag: '🇮🇸' },
  'IT': { code: '+39', name: 'Italy', flag: '🇮🇹' },
  'JE': { code: '+44', name: 'Jersey', flag: '🇯🇪' },
  'JM': { code: '+1', name: 'Jamaica', flag: '🇯🇲' },
  'JO': { code: '+962', name: 'Jordan', flag: '🇯🇴' },
  'JP': { code: '+81', name: 'Japan', flag: '🇯🇵' },
  'KE': { code: '+254', name: 'Kenya', flag: '🇰🇪' },
  'KG': { code: '+996', name: 'Kyrgyzstan', flag: '🇰🇬' },
  'KH': { code: '+855', name: 'Cambodia', flag: '🇰🇭' },
  'KI': { code: '+686', name: 'Kiribati', flag: '🇰🇮' },
  'KM': { code: '+269', name: 'Comoros', flag: '🇰🇲' },
  'KN': { code: '+1', name: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  'KP': { code: '+850', name: 'North Korea', flag: '🇰🇵' },
  'KR': { code: '+82', name: 'South Korea', flag: '🇰🇷' },
  'KW': { code: '+965', name: 'Kuwait', flag: '🇰🇼' },
  'KY': { code: '+1', name: 'Cayman Islands', flag: '🇰🇾' },
  'KZ': { code: '+7', name: 'Kazakhstan', flag: '🇰🇿' },
  'LA': { code: '+856', name: 'Laos', flag: '🇱🇦' },
  'LB': { code: '+961', name: 'Lebanon', flag: '🇱🇧' },
  'LC': { code: '+1', name: 'Saint Lucia', flag: '🇱🇨' },
  'LI': { code: '+423', name: 'Liechtenstein', flag: '🇱🇮' },
  'LK': { code: '+94', name: 'Sri Lanka', flag: '🇱🇰' },
  'LR': { code: '+231', name: 'Liberia', flag: '🇱🇷' },
  'LS': { code: '+266', name: 'Lesotho', flag: '🇱🇸' },
  'LT': { code: '+370', name: 'Lithuania', flag: '🇱🇹' },
  'LU': { code: '+352', name: 'Luxembourg', flag: '🇱🇺' },
  'LV': { code: '+371', name: 'Latvia', flag: '🇱🇻' },
  'LY': { code: '+218', name: 'Libya', flag: '🇱🇾' },
  'MA': { code: '+212', name: 'Morocco', flag: '🇲🇦' },
  'MC': { code: '+377', name: 'Monaco', flag: '🇲🇨' },
  'MD': { code: '+373', name: 'Moldova', flag: '🇲🇩' },
  'ME': { code: '+382', name: 'Montenegro', flag: '🇲🇪' },
  'MF': { code: '+590', name: 'Saint Martin', flag: '🇲🇫' },
  'MG': { code: '+261', name: 'Madagascar', flag: '🇲🇬' },
  'MH': { code: '+692', name: 'Marshall Islands', flag: '🇲🇭' },
  'MK': { code: '+389', name: 'North Macedonia', flag: '🇲🇰' },
  'ML': { code: '+223', name: 'Mali', flag: '🇲🇱' },
  'MM': { code: '+95', name: 'Myanmar', flag: '🇲🇲' },
  'MN': { code: '+976', name: 'Mongolia', flag: '🇲🇳' },
  'MO': { code: '+853', name: 'Macau', flag: '🇲🇴' },
  'MP': { code: '+1', name: 'Northern Mariana Islands', flag: '🇲🇵' },
  'MQ': { code: '+596', name: 'Martinique', flag: '🇲🇶' },
  'MR': { code: '+222', name: 'Mauritania', flag: '🇲🇷' },
  'MS': { code: '+1', name: 'Montserrat', flag: '🇲🇸' },
  'MT': { code: '+356', name: 'Malta', flag: '🇲🇹' },
  'MU': { code: '+230', name: 'Mauritius', flag: '🇲🇺' },
  'MV': { code: '+960', name: 'Maldives', flag: '🇲🇻' },
  'MW': { code: '+265', name: 'Malawi', flag: '🇲🇼' },
  'MX': { code: '+52', name: 'Mexico', flag: '🇲🇽' },
  'MY': { code: '+60', name: 'Malaysia', flag: '🇲🇾' },
  'MZ': { code: '+258', name: 'Mozambique', flag: '🇲🇿' },
  'NA': { code: '+264', name: 'Namibia', flag: '🇳🇦' },
  'NC': { code: '+687', name: 'New Caledonia', flag: '🇳🇨' },
  'NE': { code: '+227', name: 'Niger', flag: '🇳🇪' },
  'NF': { code: '+672', name: 'Norfolk Island', flag: '🇳🇫' },
  'NG': { code: '+234', name: 'Nigeria', flag: '🇳🇬' },
  'NI': { code: '+505', name: 'Nicaragua', flag: '🇳🇮' },
  'NL': { code: '+31', name: 'Netherlands', flag: '🇳🇱' },
  'NO': { code: '+47', name: 'Norway', flag: '🇳🇴' },
  'NP': { code: '+977', name: 'Nepal', flag: '🇳🇵' },
  'NR': { code: '+674', name: 'Nauru', flag: '🇳🇷' },
  'NU': { code: '+683', name: 'Niue', flag: '🇳🇺' },
  'NZ': { code: '+64', name: 'New Zealand', flag: '🇳🇿' },
  'OM': { code: '+968', name: 'Oman', flag: '🇴🇲' },
  'PA': { code: '+507', name: 'Panama', flag: '🇵🇦' },
  'PE': { code: '+51', name: 'Peru', flag: '🇵🇪' },
  'PF': { code: '+689', name: 'French Polynesia', flag: '🇵🇫' },
  'PG': { code: '+675', name: 'Papua New Guinea', flag: '🇵🇬' },
  'PH': { code: '+63', name: 'Philippines', flag: '🇵🇭' },
  'PK': { code: '+92', name: 'Pakistan', flag: '🇵🇰' },
  'PL': { code: '+48', name: 'Poland', flag: '🇵🇱' },
  'PM': { code: '+508', name: 'Saint Pierre and Miquelon', flag: '🇵🇲' },
  'PN': { code: '+64', name: 'Pitcairn', flag: '🇵🇳' },
  'PR': { code: '+1', name: 'Puerto Rico', flag: '🇵🇷' },
  'PS': { code: '+970', name: 'Palestine', flag: '🇵🇸' },
  'PT': { code: '+351', name: 'Portugal', flag: '🇵🇹' },
  'PW': { code: '+680', name: 'Palau', flag: '🇵🇼' },
  'PY': { code: '+595', name: 'Paraguay', flag: '🇵🇾' },
  'QA': { code: '+974', name: 'Qatar', flag: '🇶🇦' },
  'RE': { code: '+262', name: 'Réunion', flag: '🇷🇪' },
  'RO': { code: '+40', name: 'Romania', flag: '🇷🇴' },
  'RS': { code: '+381', name: 'Serbia', flag: '🇷🇸' },
  'RU': { code: '+7', name: 'Russia', flag: '🇷🇺' },
  'RW': { code: '+250', name: 'Rwanda', flag: '🇷🇼' },
  'SA': { code: '+966', name: 'Saudi Arabia', flag: '🇸🇦' },
  'SB': { code: '+677', name: 'Solomon Islands', flag: '🇸🇧' },
  'SC': { code: '+248', name: 'Seychelles', flag: '🇸🇨' },
  'SD': { code: '+249', name: 'Sudan', flag: '🇸🇩' },
  'SE': { code: '+46', name: 'Sweden', flag: '🇸🇪' },
  'SG': { code: '+65', name: 'Singapore', flag: '🇸🇬' },
  'SH': { code: '+290', name: 'Saint Helena', flag: '🇸🇭' },
  'SI': { code: '+386', name: 'Slovenia', flag: '🇸🇮' },
  'SJ': { code: '+47', name: 'Svalbard and Jan Mayen', flag: '🇸🇯' },
  'SK': { code: '+421', name: 'Slovakia', flag: '🇸🇰' },
  'SL': { code: '+232', name: 'Sierra Leone', flag: '🇸🇱' },
  'SM': { code: '+378', name: 'San Marino', flag: '🇸🇲' },
  'SN': { code: '+221', name: 'Senegal', flag: '🇸🇳' },
  'SO': { code: '+252', name: 'Somalia', flag: '🇸🇴' },
  'SR': { code: '+597', name: 'Suriname', flag: '🇸🇷' },
  'SS': { code: '+211', name: 'South Sudan', flag: '🇸🇸' },
  'ST': { code: '+239', name: 'São Tomé and Príncipe', flag: '🇸🇹' },
  'SV': { code: '+503', name: 'El Salvador', flag: '🇸🇻' },
  'SX': { code: '+1', name: 'Sint Maarten', flag: '🇸🇽' },
  'SY': { code: '+963', name: 'Syria', flag: '🇸🇾' },
  'SZ': { code: '+268', name: 'Eswatini', flag: '🇸🇿' },
  'TC': { code: '+1', name: 'Turks and Caicos Islands', flag: '🇹🇨' },
  'TD': { code: '+235', name: 'Chad', flag: '🇹🇩' },
  'TF': { code: '+262', name: 'French Southern Territories', flag: '🇹🇫' },
  'TG': { code: '+228', name: 'Togo', flag: '🇹🇬' },
  'TH': { code: '+66', name: 'Thailand', flag: '🇹🇭' },
  'TJ': { code: '+992', name: 'Tajikistan', flag: '🇹🇯' },
  'TK': { code: '+690', name: 'Tokelau', flag: '🇹🇰' },
  'TL': { code: '+670', name: 'East Timor', flag: '🇹🇱' },
  'TM': { code: '+993', name: 'Turkmenistan', flag: '🇹🇲' },
  'TN': { code: '+216', name: 'Tunisia', flag: '🇹🇳' },
  'TO': { code: '+676', name: 'Tonga', flag: '🇹🇴' },
  'TR': { code: '+90', name: 'Turkey', flag: '🇹🇷' },
  'TT': { code: '+1', name: 'Trinidad and Tobago', flag: '🇹🇹' },
  'TV': { code: '+688', name: 'Tuvalu', flag: '🇹🇻' },
  'TW': { code: '+886', name: 'Taiwan', flag: '🇹🇼' },
  'TZ': { code: '+255', name: 'Tanzania', flag: '🇹🇿' },
  'UA': { code: '+380', name: 'Ukraine', flag: '🇺🇦' },
  'UG': { code: '+256', name: 'Uganda', flag: '🇺🇬' },
  'UM': { code: '+1', name: 'U.S. Outlying Islands', flag: '🇺🇲' },
  'US': { code: '+1', name: 'United States', flag: '🇺🇸' },
  'UY': { code: '+598', name: 'Uruguay', flag: '🇺🇾' },
  'UZ': { code: '+994', name: 'Uzbekistan', flag: '🇺🇿' },
  'VA': { code: '+39', name: 'Vatican City', flag: '🇻🇦' },
  'VC': { code: '+1', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
  'VE': { code: '+58', name: 'Venezuela', flag: '🇻🇪' },
  'VG': { code: '+1', name: 'British Virgin Islands', flag: '🇻🇬' },
  'VI': { code: '+1', name: 'U.S. Virgin Islands', flag: '🇻🇮' },
  'VN': { code: '+84', name: 'Vietnam', flag: '🇻🇳' },
  'VU': { code: '+678', name: 'Vanuatu', flag: '🇻🇺' },
  'WF': { code: '+681', name: 'Wallis and Futuna', flag: '🇼🇫' },
  'WS': { code: '+685', name: 'Samoa', flag: '🇼🇸' },
  'XK': { code: '+383', name: 'Kosovo', flag: '🇽🇰' },
  'YE': { code: '+967', name: 'Yemen', flag: '🇾🇪' },
  'YT': { code: '+262', name: 'Mayotte', flag: '🇾🇹' },
  'ZA': { code: '+27', name: 'South Africa', flag: '🇿🇦' },
  'ZM': { code: '+260', name: 'Zambia', flag: '🇿🇲' },
  'ZW': { code: '+263', name: 'Zimbabwe', flag: '🇿🇼' },
}

export const DEFAULT_COUNTRY = 'IN'
export const DEFAULT_COUNTRY_CODE = '+91'

export function getCountryCode(countryIso: string): string {
  return COUNTRY_CODES[countryIso]?.code || DEFAULT_COUNTRY_CODE
}

export function formatPhoneWithCountryCode(phone: string, countryCode: string): string {
  // Remove any whitespace, +, dashes, parentheses
  let cleaned = phone.trim().replace(/\s+/g, '').replace(/-/g, '').replace(/\(/g, '').replace(/\)/g, '')
  
  // Remove any non-digit characters to get just the phone digits
  const phoneDigits = cleaned.replace(/\D/g, '')
  
  if (!phoneDigits) return phone
  
  // If country code is provided, use it directly - don't try to detect from phone number
  const codeDigits = countryCode.replace('+', '')
  
  // Remove leading 0 if present (common in India)
  let localNumber = phoneDigits
  if (localNumber.startsWith('0') && countryCode === '+91') {
    localNumber = localNumber.slice(1)
  }
  
  // If phone already starts with country code digits, remove them to get local number
  if (localNumber.startsWith(codeDigits)) {
    localNumber = localNumber.slice(codeDigits.length)
  }
  
  // Return formatted phone with country code
  return `+${codeDigits}${localNumber}`
}

