# Generated by Django 4.2.7 on 2025-11-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
